spring:
  datasource:
    url: jdbc:mysql://mysql:3306/myvlog?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:123456}
  sql:
    init:
      mode: never

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl # 生产环境关闭日志

logging:
  level:
    root: info
    com.myvlog.blog: info
